services:
  publisher:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  postgres:
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_username
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_db
      - postgres_password
      - postgres_username
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  prometheus:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    command:
      - --storage.tsdb.retention.time=${PROM_RETENTION}

  grafana:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
    secrets:
      - grafana_admin_password

  nginx:
    image: nginx:stable-alpine
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - publisher
      - grafana
    networks:
      - app-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

secrets:
  postgres_password:
    file: ../../.secrets/postgres/postgres_password.txt
  postgres_db:
    file: ../../.secrets/postgres/postgres_db.txt
  postgres_username:
    file: ../../.secrets/postgres/postgres_username.txt
  grafana_admin_password:
    file: ../../.secrets/grafana/grafana_admin_password.txt
