services:
  publisher:
    environment:
      EVENT_ENDPOINT: ${EVENT_ENDPOINT}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  postgres:
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_username
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_username
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  prometheus:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    command:
      - --storage.tsdb.retention.time=${PROM_RETENTION}

  grafana:
    environment:
      GF_SECURITY_ADMIN_PASSWORD:
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
    secrets:
      - grafana_admin_password
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # We might also mount SSL certificates for HTTPS in the future
#      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - publisher
      - grafana
    networks:
      - app-network
      - monitoring
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 64M

  nats:
    environment:
      NATS_USER: ${NATS_USER}
      NATS_PASSWORD_FILE: /run/secrets/nats_password
    secrets:
      - nats_password
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

secrets:
  postgres_password:
    file: ../../.secrets/postgres/postgres_password.txt
  postgres_db:
    file: ../../.secrets/postgres/postgres_db.txt
  postgres_username:
    file: ../../.secrets/postgres/postgres_username.txt
  grafana_admin_password:
    file: ../../.secrets/grafana/grafana_admin_password.txt
  nats_password:
    file: ../../.secrets/nats/nats_password.txt
