global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "publisher"
    static_configs:
      - targets: ["publisher:8080"]
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8000"]
    metrics_path: "/metrics"

  - job_name: "reporter"
    static_configs:
      - targets: ["reporter:8001"]
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fb-collector"
    scrape_interval: 1m
    static_configs:
      - targets: ["fb-collector:8003"]
    metrics_path: "/metrics"

  - job_name: "ttk-collector"
    scrape_interval: 1m
    static_configs:
      - targets: ["ttk-collector:8004"]
    metrics_path: "/metrics"